# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: DISTRIB="ubuntu" TOX_PYTHON_VERSION="py37" COVERAGE="true"
    - env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="false"
install:
  - pip install pipenv
  - pipenv install
  # ^  DEPRECATION WARNING:
  # The automatic creation of a `requirements.txt` file is deprecated.
  # See `Dependency Management` in the docs for other options.
before_script:
  - git config user.email "mr.fedotovaleksandr@gmail.com"
  - git config user.name "fedotovaleksandr"
script:
  - python setup.py develop
  - tox
  - |
    if [[ "$COVERAGE" == "true" ]]; then
      pre-commit install
      pre-commit run --all-files
    fi
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - pipenv --rm
cache:
  pip: true
